# Site settings
name: reachal
email: akinada505@gmail.com
url: url
description: "A blog and a portfolio"
author: "reachal"
title: "Blog"
permalink: pretty
baseurl: /

# social
github:
  username: reachal0206

twitter:
  username: username